package org.apache.jsp.system.logon;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class head_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');

String path = request.getContextPath();

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"utf-8\">\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("  <title>AdminLTE 2 | Dashboard</title>\n");
      out.write("  <!-- Tell the browser to be responsive to screen width -->\n");
      out.write("  <meta content=\"width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no\" name=\"viewport\">\n");
      out.write("  <!-- Bootstrap 3.3.7 -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.print(path);
      out.write("/mirrors-adminlte-master/adminlte/bower_components/bootstrap/dist/css/bootstrap.min.css\">\n");
      out.write("  <!-- Font Awesome -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.print(path);
      out.write("/mirrors-adminlte-master/adminlte/bower_components/font-awesome/css/font-awesome.min.css\">\n");
      out.write("  <!-- Ionicons -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.print(path);
      out.write("/mirrors-adminlte-master/adminlte/bower_components/Ionicons/css/ionicons.min.css\">\n");
      out.write("  <!-- Theme style -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.print(path);
      out.write("/mirrors-adminlte-master/adminlte/dist/css/AdminLTE.min.css\">\n");
      out.write("  <!-- AdminLTE Skins. Choose a skin from the css/skins\n");
      out.write("       folder instead of downloading all of them to reduce the load. -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.print(path);
      out.write("/mirrors-adminlte-master/adminlte/dist/css/skins/_all-skins.min.css\">\n");
      out.write("  <!-- Morris chart -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.print(path);
      out.write("/mirrors-adminlte-master/adminlte/bower_components/morris.js/morris.css\">\n");
      out.write("  <!-- jvectormap -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.print(path);
      out.write("/mirrors-adminlte-master/adminlte/bower_components/jvectormap/jquery-jvectormap.css\">\n");
      out.write("  <!-- Date Picker -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.print(path);
      out.write("/mirrors-adminlte-master/adminlte/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css\">\n");
      out.write("  <!-- Daterange picker -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.print(path);
      out.write("/mirrors-adminlte-master/adminlte/bower_components/bootstrap-daterangepicker/daterangepicker.css\">\n");
      out.write("  <!-- bootstrap wysihtml5 - text editor -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.print(path);
      out.write("/mirrors-adminlte-master/adminlte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css\">\n");
      out.write("\n");
      out.write("  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\n");
      out.write("  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\n");
      out.write("  <!--[if lt IE 9]>\n");
      out.write("  <script src=\"https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js\"></script>\n");
      out.write("  <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\n");
      out.write("  <![endif]-->\n");
      out.write("\n");
      out.write("  <!-- Google Font -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic\">\n");
      out.write("\n");
      out.write("<!-- jQuery 3 -->\n");
      out.write("<script src=\"");
      out.print(path);
      out.write("/mirrors-adminlte-master/adminlte/bower_components/jquery/dist/jquery.min.js\"></script>\n");
      out.write("<!-- jQuery UI 1.11.4 -->\n");
      out.write("<script src=\"");
      out.print(path);
      out.write("/mirrors-adminlte-master/adminlte/bower_components/jquery-ui/jquery-ui.min.js\"></script>\n");
      out.write("<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->\n");
      out.write("\n");
      out.write("<!-- Bootstrap 3.3.7 -->\n");
      out.write("<script src=\"");
      out.print(path);
      out.write("/mirrors-adminlte-master/adminlte/bower_components/bootstrap/dist/js/bootstrap.min.js\"></script>\n");
      out.write("<!-- Morris.js charts -->\n");
      out.write("<script src=\"");
      out.print(path);
      out.write("/mirrors-adminlte-master/adminlte/bower_components/raphael/raphael.min.js\"></script>\n");
      out.write("<script src=\"");
      out.print(path);
      out.write("/mirrors-adminlte-master/adminlte/bower_components/morris.js/morris.min.js\"></script>\n");
      out.write("<!-- Sparkline -->\n");
      out.write("<script src=\"");
      out.print(path);
      out.write("/mirrors-adminlte-master/adminlte/bower_components/jquery-sparkline/dist/jquery.sparkline.min.js\"></script>\n");
      out.write("<!-- jvectormap -->\n");
      out.write("<script src=\"");
      out.print(path);
      out.write("/mirrors-adminlte-master/adminlte/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js\"></script>\n");
      out.write("<script src=\"");
      out.print(path);
      out.write("/mirrors-adminlte-master/adminlte/plugins/jvectormap/jquery-jvectormap-world-mill-en.js\"></script>\n");
      out.write("<!-- jQuery Knob Chart -->\n");
      out.write("<script src=\"");
      out.print(path);
      out.write("/mirrors-adminlte-master/adminlte/bower_components/jquery-knob/dist/jquery.knob.min.js\"></script>\n");
      out.write("<!-- daterangepicker -->\n");
      out.write("<script src=\"");
      out.print(path);
      out.write("/mirrors-adminlte-master/adminlte/bower_components/moment/min/moment.min.js\"></script>\n");
      out.write("<script src=\"");
      out.print(path);
      out.write("/mirrors-adminlte-master/adminlte/bower_components/bootstrap-daterangepicker/daterangepicker.js\"></script>\n");
      out.write("<!-- datepicker -->\n");
      out.write("<script src=\"");
      out.print(path);
      out.write("/mirrors-adminlte-master/adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js\"></script>\n");
      out.write("<!-- Bootstrap WYSIHTML5 -->\n");
      out.write("<script src=\"");
      out.print(path);
      out.write("/mirrors-adminlte-master/adminlte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js\"></script>\n");
      out.write("<!-- Slimscroll -->\n");
      out.write("<script src=\"");
      out.print(path);
      out.write("/mirrors-adminlte-master/adminlte/bower_components/jquery-slimscroll/jquery.slimscroll.min.js\"></script>\n");
      out.write("<!-- FastClick -->\n");
      out.write("<script src=\"");
      out.print(path);
      out.write("/mirrors-adminlte-master/adminlte/bower_components/fastclick/lib/fastclick.js\"></script>\n");
      out.write("<!-- AdminLTE App -->\n");
      out.write("<script src=\"");
      out.print(path);
      out.write("/mirrors-adminlte-master/adminlte/dist/js/adminlte.min.js\"></script>\n");
      out.write("<!-- AdminLTE dashboard demo (This is only for demo purposes) -->\n");
      out.write("<script src=\"");
      out.print(path);
      out.write("/mirrors-adminlte-master/adminlte/dist/js/pages/dashboard.js\"></script>\n");
      out.write("<!-- AdminLTE for demo purposes -->\n");
      out.write("<script src=\"");
      out.print(path);
      out.write("/mirrors-adminlte-master/adminlte/dist/js/demo.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<div class=\"navbar-custom-menu\">\n");
      out.write("\t<ul class=\"nav navbar-nav\">\n");
      out.write("         <!-- Messages: style can be found in dropdown.less-->\n");
      out.write("    <li class=\"dropdown messages-menu\">\n");
      out.write("      <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">\n");
      out.write("        <i class=\"fa fa-envelope-o\"></i>\n");
      out.write("        <span class=\"label label-success\">4</span>\n");
      out.write("      </a>\n");
      out.write("      <ul class=\"dropdown-menu\">\n");
      out.write("        <li class=\"header\">You have 4 messages</li>\n");
      out.write("        <li>\n");
      out.write("          <!-- inner menu: contains the actual data -->\n");
      out.write("          <ul class=\"menu\">\n");
      out.write("            <li><!-- start message -->\n");
      out.write("              <a href=\"#\">\n");
      out.write("                <div class=\"pull-left\">\n");
      out.write("                  <img src=\"dist/img/user2-160x160.jpg\" class=\"img-circle\" alt=\"User Image\">\n");
      out.write("                </div>\n");
      out.write("                <h4>\n");
      out.write("                  Support Team\n");
      out.write("                  <small><i class=\"fa fa-clock-o\"></i> 5 mins</small>\n");
      out.write("                </h4>\n");
      out.write("                <p>Why not buy a new awesome theme?</p>\n");
      out.write("              </a>\n");
      out.write("            </li>\n");
      out.write("            <!-- end message -->\n");
      out.write("            <li>\n");
      out.write("              <a href=\"#\">\n");
      out.write("                <div class=\"pull-left\">\n");
      out.write("                  <img src=\"dist/img/user3-128x128.jpg\" class=\"img-circle\" alt=\"User Image\">\n");
      out.write("                </div>\n");
      out.write("                <h4>\n");
      out.write("                  AdminLTE Design Team\n");
      out.write("                  <small><i class=\"fa fa-clock-o\"></i> 2 hours</small>\n");
      out.write("                </h4>\n");
      out.write("                <p>Why not buy a new awesome theme?</p>\n");
      out.write("              </a>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("              <a href=\"#\">\n");
      out.write("                <div class=\"pull-left\">\n");
      out.write("                  <img src=\"dist/img/user4-128x128.jpg\" class=\"img-circle\" alt=\"User Image\">\n");
      out.write("                </div>\n");
      out.write("                <h4>\n");
      out.write("                  Developers\n");
      out.write("                  <small><i class=\"fa fa-clock-o\"></i> Today</small>\n");
      out.write("                </h4>\n");
      out.write("                <p>Why not buy a new awesome theme?</p>\n");
      out.write("              </a>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("              <a href=\"#\">\n");
      out.write("                <div class=\"pull-left\">\n");
      out.write("                  <img src=\"dist/img/user3-128x128.jpg\" class=\"img-circle\" alt=\"User Image\">\n");
      out.write("                </div>\n");
      out.write("                <h4>\n");
      out.write("                  Sales Department\n");
      out.write("                  <small><i class=\"fa fa-clock-o\"></i> Yesterday</small>\n");
      out.write("                </h4>\n");
      out.write("                <p>Why not buy a new awesome theme?</p>\n");
      out.write("              </a>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("              <a href=\"#\">\n");
      out.write("                <div class=\"pull-left\">\n");
      out.write("                  <img src=\"dist/img/user4-128x128.jpg\" class=\"img-circle\" alt=\"User Image\">\n");
      out.write("                </div>\n");
      out.write("                <h4>\n");
      out.write("                  Reviewers\n");
      out.write("                  <small><i class=\"fa fa-clock-o\"></i> 2 days</small>\n");
      out.write("                </h4>\n");
      out.write("                <p>Why not buy a new awesome theme?</p>\n");
      out.write("              </a>\n");
      out.write("            </li>\n");
      out.write("          </ul>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"footer\"><a href=\"#\">See All Messages</a></li>\n");
      out.write("      </ul>\n");
      out.write("    </li>\n");
      out.write("    <!-- Notifications: style can be found in dropdown.less -->\n");
      out.write("    <li class=\"dropdown notifications-menu\">\n");
      out.write("      <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">\n");
      out.write("        <i class=\"fa fa-bell-o\"></i>\n");
      out.write("        <span class=\"label label-warning\">10</span>\n");
      out.write("      </a>\n");
      out.write("      <ul class=\"dropdown-menu\">\n");
      out.write("        <li class=\"header\">You have 10 notifications</li>\n");
      out.write("        <li>\n");
      out.write("          <!-- inner menu: contains the actual data -->\n");
      out.write("          <ul class=\"menu\">\n");
      out.write("            <li>\n");
      out.write("              <a href=\"#\">\n");
      out.write("                <i class=\"fa fa-users text-aqua\"></i> 5 new members joined today\n");
      out.write("              </a>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("              <a href=\"#\">\n");
      out.write("                <i class=\"fa fa-warning text-yellow\"></i> Very long description here that may not fit into the\n");
      out.write("                page and may cause design problems\n");
      out.write("              </a>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("              <a href=\"#\">\n");
      out.write("                <i class=\"fa fa-users text-red\"></i> 5 new members joined\n");
      out.write("              </a>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("              <a href=\"#\">\n");
      out.write("                <i class=\"fa fa-shopping-cart text-green\"></i> 25 sales made\n");
      out.write("              </a>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("              <a href=\"#\">\n");
      out.write("                <i class=\"fa fa-user text-red\"></i> You changed your username\n");
      out.write("              </a>\n");
      out.write("            </li>\n");
      out.write("          </ul>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"footer\"><a href=\"#\">View all</a></li>\n");
      out.write("      </ul>\n");
      out.write("    </li>\n");
      out.write("    <!-- Tasks: style can be found in dropdown.less -->\n");
      out.write("    <li class=\"dropdown tasks-menu\">\n");
      out.write("      <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">\n");
      out.write("        <i class=\"fa fa-flag-o\"></i>\n");
      out.write("        <span class=\"label label-danger\">9</span>\n");
      out.write("      </a>\n");
      out.write("      <ul class=\"dropdown-menu\">\n");
      out.write("        <li class=\"header\">You have 9 tasks</li>\n");
      out.write("        <li>\n");
      out.write("          <!-- inner menu: contains the actual data -->\n");
      out.write("          <ul class=\"menu\">\n");
      out.write("            <li><!-- Task item -->\n");
      out.write("              <a href=\"#\">\n");
      out.write("                <h3>\n");
      out.write("                  Design some buttons\n");
      out.write("                  <small class=\"pull-right\">20%</small>\n");
      out.write("                </h3>\n");
      out.write("                <div class=\"progress xs\">\n");
      out.write("                  <div class=\"progress-bar progress-bar-aqua\" style=\"width: 20%\" role=\"progressbar\"\n");
      out.write("                       aria-valuenow=\"20\" aria-valuemin=\"0\" aria-valuemax=\"100\">\n");
      out.write("                    <span class=\"sr-only\">20% Complete</span>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              </a>\n");
      out.write("            </li>\n");
      out.write("            <!-- end task item -->\n");
      out.write("            <li><!-- Task item -->\n");
      out.write("              <a href=\"#\">\n");
      out.write("                <h3>\n");
      out.write("                  Create a nice theme\n");
      out.write("                  <small class=\"pull-right\">40%</small>\n");
      out.write("                </h3>\n");
      out.write("                <div class=\"progress xs\">\n");
      out.write("                  <div class=\"progress-bar progress-bar-green\" style=\"width: 40%\" role=\"progressbar\"\n");
      out.write("                       aria-valuenow=\"20\" aria-valuemin=\"0\" aria-valuemax=\"100\">\n");
      out.write("                    <span class=\"sr-only\">40% Complete</span>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              </a>\n");
      out.write("            </li>\n");
      out.write("            <!-- end task item -->\n");
      out.write("            <li><!-- Task item -->\n");
      out.write("              <a href=\"#\">\n");
      out.write("                <h3>\n");
      out.write("                  Some task I need to do\n");
      out.write("                  <small class=\"pull-right\">60%</small>\n");
      out.write("                </h3>\n");
      out.write("                <div class=\"progress xs\">\n");
      out.write("                  <div class=\"progress-bar progress-bar-red\" style=\"width: 60%\" role=\"progressbar\"\n");
      out.write("                       aria-valuenow=\"20\" aria-valuemin=\"0\" aria-valuemax=\"100\">\n");
      out.write("                    <span class=\"sr-only\">60% Complete</span>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              </a>\n");
      out.write("            </li>\n");
      out.write("            <!-- end task item -->\n");
      out.write("            <li><!-- Task item -->\n");
      out.write("              <a href=\"#\">\n");
      out.write("                <h3>\n");
      out.write("                  Make beautiful transitions\n");
      out.write("                  <small class=\"pull-right\">80%</small>\n");
      out.write("                </h3>\n");
      out.write("                <div class=\"progress xs\">\n");
      out.write("                  <div class=\"progress-bar progress-bar-yellow\" style=\"width: 80%\" role=\"progressbar\"\n");
      out.write("                       aria-valuenow=\"20\" aria-valuemin=\"0\" aria-valuemax=\"100\">\n");
      out.write("                    <span class=\"sr-only\">80% Complete</span>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              </a>\n");
      out.write("            </li>\n");
      out.write("            <!-- end task item -->\n");
      out.write("          </ul>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"footer\">\n");
      out.write("          <a href=\"#\">View all tasks</a>\n");
      out.write("        </li>\n");
      out.write("      </ul>\n");
      out.write("    </li>\n");
      out.write("    <!-- User Account: style can be found in dropdown.less -->\n");
      out.write("    <li class=\"dropdown user user-menu\">\n");
      out.write("      <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">\n");
      out.write("        <img src=\"dist/img/user2-160x160.jpg\" class=\"user-image\" alt=\"User Image\">\n");
      out.write("        <span class=\"hidden-xs\">Alexander Pierce</span>\n");
      out.write("      </a>\n");
      out.write("      <ul class=\"dropdown-menu\">\n");
      out.write("        <!-- User image -->\n");
      out.write("        <li class=\"user-header\">\n");
      out.write("          <img src=\"dist/img/user2-160x160.jpg\" class=\"img-circle\" alt=\"User Image\">\n");
      out.write("\n");
      out.write("          <p>\n");
      out.write("            Alexander Pierce - Web Developer\n");
      out.write("            <small>Member since Nov. 2012</small>\n");
      out.write("          </p>\n");
      out.write("        </li>\n");
      out.write("        <!-- Menu Body -->\n");
      out.write("        <li class=\"user-body\">\n");
      out.write("          <div class=\"row\">\n");
      out.write("            <div class=\"col-xs-4 text-center\">\n");
      out.write("              <a href=\"#\">Followers</a>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-xs-4 text-center\">\n");
      out.write("              <a href=\"#\">Sales</a>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-xs-4 text-center\">\n");
      out.write("              <a href=\"#\">Friends</a>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <!-- /.row -->\n");
      out.write("        </li>\n");
      out.write("        <!-- Menu Footer-->\n");
      out.write("        <li class=\"user-footer\">\n");
      out.write("          <div class=\"pull-left\">\n");
      out.write("            <a href=\"#\" class=\"btn btn-default btn-flat\">Profile</a>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"pull-right\">\n");
      out.write("            <a href=\"#\" class=\"btn btn-default btn-flat\">Sign out</a>\n");
      out.write("          </div>\n");
      out.write("        </li>\n");
      out.write("      </ul>\n");
      out.write("    </li>\n");
      out.write("    <!-- Control Sidebar Toggle Button -->\n");
      out.write("    <li>\n");
      out.write("      <a href=\"#\" data-toggle=\"control-sidebar\"><i class=\"fa fa-gears\"></i></a>\n");
      out.write("    </li>\n");
      out.write("  </ul>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else log(t.getMessage(), t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
